#----------------------------------------------------
# Release pipeline test version
# ---------------------------------------------------

name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # For PyPI trusted publishing

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important for commitizen

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install deps
        run: uv sync --all-extras

      - name: Run commitizen bump
        run: uv run cz bump --yes
        env:
          CZ_USE_COMMITIZEN: "true"

      - name: Push changes back to source branch
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          git push --follow-tags origin HEAD:${REF_NAME}

      # Optional: publish to PyPI using trusted publisher
      # extention point not implemented yet